sudo: required
services:
    - docker

before_install:
    - docker build -t andrarajo/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true andrarajo/react-test npm run test

after_success:
    - docker build -t andrarajo/multi-client ./client
    - docker build -t andrarajo/multi-nginx ./nginx
    - docker build -t andrarajo/multi-server ./server
    - docker build -t andrarajo/multi-worker ./worker
    # Log in no docker CLI
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    # Pegar cada imagem e colocar no docker hub
    - docker push andrarajo/multi-client
    - docker push andrarajo/multi-nginx
    - docker push andrarajo/multi-server
    - docker push andrarajo/multi-worker